### ISSUE TITLE
this.maps[key].addAnnotation is not a function

### ISSUE THREAD

**Issue by muuvmuuv** [webtimo-de/ngx-apple-mapkit#2]
When navigating between pages that have resolvers and guards, it sometimes happens that `this.maps` has not yet registered the map and annotation fails.

I tried to wait for `map` already, but this does not help.

```ts
<ngx-apple-mapkit
  *ngIf="options"
  [options]="options"
  [settings]="settings"
  (onLoaded)="map = $event"
>
  <ng-container *ngIf="map">
    <ngx-apple-mapkit-annotation
      *ngIf="marker && coordinates"
      [latitude]="coordinates.latitude"
      [longitude]="coordinates.longitude"
      [options]="{ animates: true }"
    >
      <img alt="" src="/assets/pins/pin.svg" />
    </ngx-apple-mapkit-annotation>
  </ng-container>
</ngx-apple-mapkit>
```

![image](https://github.com/webtimo-de/ngx-apple-mapkit/assets/11534760/9e7fd8ad-bdbe-4cf9-b90a-c76d0bb9d0f4)

**Comment by webtimo-de** [comment]
```typescript
<ngx-apple-mapkit id="map-apple"
                  (onLoaded)="onLoaded($event)"
                  *ngIf="!!options && !!settings"
                  [options]="options" [settings]="settings">
    <ng-container *ngIf="map">
        <ngx-apple-mapkit-annotation
                [options]="{animates: true}"
                [latitude]="51.6815333"
                [longitude]="7.8637212"
        >
            <img alt="" src="https://...../brand/icon.svg" />
        </ngx-apple-mapkit-annotation>
    </ng-container>
</ngx-apple-mapkit>
```

I just tried to recreate this and I have no problems. Can you maybe give me more context?

**Comment by muuvmuuv** [comment]
I define options after I fetched the jwt token so map will be displayed after. 

The example above is simplyfied, here is the full onMapLoaded:

```ts
  protected onMapLoaded(map: Map) {
    this.log.debug(StackFeatures.Map, 'Map loaded', map)

    map.map.addEventListener('region-change-end', (data: { target: MapKitImpl }) => {
      this.cameraMoved.emit({
        latitude: data.target.center.latitude,
        longitude: data.target.center.longitude,
        zoom: Math.round(data.target._impl.zoomLevel),
      })
    })

    map.map._impl.zoomLevel = this.zoom

    if (this.showUser) {
      this.settings.showsUserLocation = true
      this.settings.showsUserLocationControl = true
      this.settings.tracksUserLocation = true
    }

    if (this.coordinates) {
      this.setCenter(this.coordinates)
    }

    this.map = map
    this.mapLoaded.emit(this)
  }
```

**Comment by webtimo-de** [comment]
Do you have the AppleMapsModule in an App.Modules.ts?

**Comment by muuvmuuv** [comment]
Nope, in the components standalone modules section.

**Comment by muuvmuuv** [comment]
Just added it in both, no change. On reload it works, it is just after navigation.

**Comment by muuvmuuv** [comment]
Ok tested displaying "ngx-apple-mapkit-annotation" after 1s with an setTimeout. Same thing. Seems its not finding its parent component.

**Comment by webtimo-de** [comment]
It may sound a bit stupid, but recompile and delete the .angular folder beforehand.

**Comment by muuvmuuv** [comment]
No, sadly no change. I logged this.maps to console and things look a bit off here: 
![image](https://github.com/webtimo-de/ngx-apple-mapkit/assets/11534760/8c195237-f7c8-4da0-afe9-506b9260ff14)
> https://github.com/webtimo-de/ngx-apple-mapkit/blob/main/esm2022/lib/apple-maps.service.mjs#L362

**Comment by webtimo-de** [comment]
I'm really confused because I honestly don't have any problems with it. It looks like he tries to load the map several times. I think with every call.

Please don't try to design this as a single component

**Comment by muuvmuuv** [comment]
I have to, all of our components are standalone. So our map component is just a wrapper with functions we need additionally.

Normally this shouldn't be the issue. I think the problem is that it always creates a new instance, because you do an "[key].push(map)", where key is just the index. If you would allow string keys with a Map, anyone can define them and mapkit would re-use the existing instance.

**Comment by webtimo-de** [comment]
Yes, okay, you're right. But this is such a fundamental change that I can't do it today. I'll sit down on it next week.

**Comment by muuvmuuv** [comment]
I would love to hepl by contributing some changes if you push the source code.

**Comment by webtimo-de** [comment]
i add you in `https://github.com/webtimo-de/ngx-apple-mapkit-library`

**Comment by muuvmuuv** [comment]
Just tested with Map... problem persists. Still I think Map is better than index and array.

**Comment by webtimo-de** [comment]
> Just tested with Map... problem persists. Still I think Map is better than index and array.

~~Show me pls~~

**Comment by webtimo-de** [comment]
Ahhh, I know what you mean, `this.map.map`
I understand, that's also why Zoom doesn't work. But I'll put it on my agenda. I think that's what he did with `ngx-apple-maps` because you can also use services. But I think you can also start it separately.
But I'll still go ahead and try to rewrite it from array/index to normal. Or to remove or improve the more complex.

**Comment by muuvmuuv** [comment]
Is it really needed to have a service? I mean, you can have a standalone component for each map that inits itself. This would avoid a lot of problems.

**Comment by webtimo-de** [comment]
Yes, I know, that's better too. Just like I said, I have to do a lot of modifications for this. 
But I will rebuild it soon.

Service: https://github.com/webtimo-de/ngx-apple-mapkit/tree/main/esm2022/lib/services

**Comment by muuvmuuv** [comment]
Wrote you back, lets close this. Have a look at my changes.
