### ISSUE TITLE
Any way to change resultTypeFilter?

### ISSUE THREAD

**Issue by jakubforman** [webtimo-de/ngx-apple-mapkit#4]
I want to change resultTypeFilter from default address to Poi or others like in [Official Apple Playground](https://maps.developer.apple.com/maps-server-api-playground). I can't because I don't find any possible solution how I can change QueryParams in request under autocomplete or search.

I want to get something like `https://maps-api.apple.com/v1/searchAutocomplete?q=Zl%C3%ADn&resultTypeFilter=Poi`

Now service generate request like `https://api.apple-mapkit.com/v1/searchAutocomplete?q=zl%C3%ADn&lang=cs&resultTypeFilter=address%2Cpoi%2Cquery&mkjsVersion=5.77.35`

Also I want to add or remove any queryParam.

Code example:

```typescript
async autocomplete(query: string): Promise<MapKitAutocompleteResult[]> {

        this.appleMapsSearchService.initSearch()

        return new Promise((resolve, reject) => {
            const options = {
                resultTypeFilter: 'Poi'
            };

            this.appleMapsSearchService.autocomplete(query, (err, data: SearchAutocompleteResponse) => {
                if (err) {
                    reject(reject);
                } else {
                    resolve(data.results as MapKitAutocompleteResult[]);
                }
            }, options as SearchInterface);
        })
    }
    
    
export interface MapKitAutocompleteResult extends SearchAutocompleteResult {
    displayLines: string[]
    coordinate: Coordinate
    _completionUrl: string
    urls: any[]
    muid?: string
    _providerId?: string
    _providerItemId?: string
    administrativeArea?: string
    administrativeAreaCode?: string
    locality?: string
    postCode?: string
    subLocality?: string
    dependentLocalities?: string[]
    timezone?: string
    timezoneSecondsFromGmt?: number
    thoroughfare?: string
    subThoroughfare?: string
    fullThoroughfare?: string
}

```

**Comment by jakubforman** [comment]
I get it, but it is not too clear to understand.

You need rewrite options and also hard retype with my original code. Afer I read documentation https://developer.apple.com/documentation/mapkitjs/searchautocompleteoptions need add `includeAddresses: false`. But options is strict to `SearchInterface`. Pless add to this interface all keys/props or us `[key: string]: string` in future update.


```typescript
const options = {
                resultTypeFilter: 'Poi',
                includeAddresses: false

            };
this.appleMapsSearchService.autocomplete(query, (err, data: SearchAutocompleteResponse) => {
                if (err) {
                    reject(reject);
                } else {
                    resolve(data.results as MapKitAutocompleteResult[]);
                }
            }, options as SearchInterface); <---- hard retype...
```

**Comment by webtimo-de** [comment]
Hi, I'll see if I can get this added.

**Comment by webtimo-de** [comment]
Can you give me an example of `MapKitAutocompleteResult._completionUrl`?

**Comment by jakubforman** [comment]
> Can you give me an example of `MapKitAutocompleteResult._completionUrl`?

I have no idea exactly where this could be used now, but the respondent API returns this data.

**Comment by webtimo-de** [comment]
You can use `mapkit.Place.urls` for this. I think. 

But I'll take a look. This sounds strongly like autocomplete.

**Comment by webtimo-de** [comment]
Hey, unfortunately I haven't found anything because of this. If you find something, you could just send me the JSON so I can see what I can do.

**Comment by jakubforman** [comment]
> Hey, unfortunately I haven't found anything because of this. If you find something, you could just send me the JSON so I can see what I can do.

Of course, if I find something, I'll send it. I haven't used the library for a while now, so I need to review what all I actually use and what comes back.

As soon as I have the output, I'll share it with you.
